name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build NestJS project
        run: npm run build

      - name: Copy files to Lightsail
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          port: 22
          source: 'dist/**,package.json,ecosystem.config.js,prisma/**'
          target: '/home/ubuntu/reservify'

      - name: SSH Deploy Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            cd /home/ubuntu/reservify
            npm install --omit=dev
            npx prisma generate
            npx prisma migrate deploy
            pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js